[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
adw = { version = "0.7.2", package = "libadwaita", features = ["v1_5"] }
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_18"] }
mainp = { version = "0.1.0", path = "../mainp" }
